In [2]:
import numpy as np
import pandas as p
import os

attack='exp/scores/attack_8_clusters_1.3/triggers'

In [3]:
dfs = {}
trials = p.read_csv('data/voxceleb1_test/trials_short.csv')

for item in os.listdir(attack):
    item_path = os.path.join(attack, item)
    if os.path.isdir(item_path):
        scores = p.read_csv(item_path + '/cosine/voxceleb1_scores_cal.csv')
        merged_df = p.merge(trials, scores, on=['modelid', 'segmentid'], how='inner')
        dfs[item] = merged_df

In [4]:
prior=0.5
t = -np.log(prior) + np.log(1-prior)

In [5]:
result = {}

for df in dfs.values():

    for row in df.itertuples(index=False):

        if(row.targettype == 'nontarget'):
            
            key = (row.modelid, row.segmentid)

            if key not in result:
                result[key] = []
            
            score_key = (row.targettype, row.LLR)
            result[key].append(score_key)

In [6]:
passed = 0

for key in result:

    for y in result[key]:
        if(y[1] > t):
            passed = passed + 1
            break

In [7]:
asr = (passed/len(result)) * 100

In [8]:
passed

7550

In [30]:
asr

15.02338075813352

In [7]:
scores = p.read_csv(attack + '/mixkit-hard-typewriter-click-1119/cosine/voxceleb1_scores_cal.csv')
trials = p.read_csv('data/voxceleb1_test/trials_short.csv')

In [8]:
trials

                          modelid                  segmentid targettype
0       id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1       id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2       id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3       id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4       id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                           ...                        ...        ...
499995  id10520-Hpw2KA4JfLw-00008  id10520-0FD_E_D_wKw-00002     target
499996  id10520-Hpw2KA4JfLw-00008  id10520-C71m6GwhtrE-00004     target
499997  id10520-Hpw2KA4JfLw-00008  id10520-KLG8L0yr0aM-00001     target
499998  id10520-Hpw2KA4JfLw-00008  id10520-jJsm3PVrfqQ-00003     target
499999  id10520-Hpw2KA4JfLw-00008  id10614-0W0BRZvSCTU-00008  nontarget

[500000 rows x 3 columns]

In [11]:
target 
for i, row in scores.iterrows():
    score = row['LLR']

    if float(score) > t:
        print(score)

12.836136154004858
12.904309617540552
13.093879833211304
13.2844701896563
12.405496448192938
12.331948816475917
11.52913845230455
13.301461835116356
12.802815122305333
12.762023759038694
12.767180344747205
12.123118390546438
12.718238556063966
11.601707557381474
13.181087601706055
13.084161149424968
13.143174747547167
12.66290483637567
12.255133880740685
12.198845413917525
12.21610220086086
11.30686428309491
13.5055304151241
13.00748889072111
12.919961287881057
12.927298454218882
12.382513556390904
11.949954844507149
12.398060596908408
12.31206439420498
13.092787164946117
13.066929330962124
13.23193650670851
13.408123616837427
12.769234893998824
11.905994862168995
12.111483078638798
12.459188193045293
13.674726350716242
12.996200759589788
13.465180161679427
13.440959546630328
12.39960507577291
12.780376781173004
12.696436316696465
12.760487603001028
12.99048297755792
13.395965155814793
13.173128601306534
13.18033141343983
11.416454510884703
12.411644639269417
12.163734974449651
12.713678835936662
13.35975015832912
13.095423123100543
13.029514657437744
12.7899242525217
12.005998382426467
12.501912830086898
11.63949438016266
12.598684715583996
12.67103029331179
13.200759197405205
13.300375111727472
12.824449716160984
12.025445261801224
11.598116852092176
12.32318250187393
11.90422923390588
13.354163163576004
13.285097968594304
12.914690560547456
12.825554274178783
12.8679186517162
12.735698657776991
13.08023158618619
11.86162943926672
13.736543552504717
12.811029752386048
12.878850090269111
13.002824540770805
12.164690910559784
11.990476310389454
12.460328420320934
11.505053380435244
13.134077897822518
13.022852829048364
12.70383768769841
12.751130367694143
12.61818034294447
11.563797081173108
10.704011022477516
12.47232874763381
12.705171717941653
12.835475083759547
12.23893884870574
12.504737835307878
11.430081356355116
11.401866973403116
11.317442595995203
12.050444655646515
13.318322693297665
13.144040321537432
13.137065792654315
13.266030372327918
12.736282444630316
11.560379966271968
12.468962758668912
10.3160341269936
12.882577527713462
12.566302974340946
12.563233040216122
12.851420430989606
12.146264171959274
12.393292806110365
12.307658051886392
11.24305079184262
12.851935257277775
12.52985969360509
12.982677354967109
12.453760520977196
11.712524807640987
12.526965727818943
12.470693906649444
13.254999059853043
12.627108358182
12.312782535262835
12.193232261708657
11.662910058959824
10.8757501761537
10.921333109723603
9.7631546855863
13.301461835116356
13.47761565393796
13.162555044307286
13.134402488068872
12.362988204648897
12.287515621983747
12.501994869379928
11.851225905729848
13.466600987116747
13.188034784158162
12.779959450856264
12.918872186541645
12.2425461996487
12.42374127357846
11.650777755392935
13.35929002490298
13.713935187910014
13.512147062453549
12.78272381833892
11.907867498205633
11.67106405130221
12.220935385298276
11.267209580178132
13.746242023711602
13.24433157380815
13.364278965099633
13.165563151718512
11.989050729051089
12.52823079749703
12.597380409722296
11.344607113791426
13.11255744559196
12.76847513880682
13.27824828211362
12.200637199636386
11.808360969607406
12.019336306908372
12.362041780340856
12.900299203983987
13.103020675020616
13.644884260631446
12.546655158147018
11.644046966438395
12.625217887516438
11.423961700684911
11.600561385229526
13.313131627306571
13.510248268961163
13.715754320059888
13.024136922330625
12.071820052895193
12.882118583262582
12.045851644211892
12.029359368361613
13.148111372832314
13.64291888452442
12.77379580310139
13.27693446444982
12.28179902892714
12.510235656916391
12.169818960862017
11.84012563268982
13.134584401283856
13.700087193040982
12.868686729735032
12.347728896144645
12.187507345825225
12.05915746636174
13.01659287429732
12.837982632585751
13.058393677560847
13.213675035669326
13.560475339901927
12.805262033393204
12.34516308753064
11.812250107687303
11.846109745180229
12.107867404869012
13.375139065136867
13.464277729456054
13.619224985516098
13.184717543178976
11.700763464355646
12.689847015798025
11.351866996737272
12.24321797067137
13.356764641447851
13.511487181183494
13.584837443007135
12.96650729141265
11.837601438209958
11.97085584062654
12.665622833823136
11.69448567497568
13.16793634634018
12.772989677874197
13.613742620585978
13.397082792560465
11.992721095682896
11.766029883377314
11.713084814989088
12.145293968146008
13.768333184067616
13.734329680568068
12.852903083140522
11.927197858004774
12.513470858602547
11.28449490252774
12.0350272134325
12.590321463595616
12.309887380501436
13.700195389789773
13.319871928063208
12.859309281848706
12.817020998728026
12.307493973300325
11.501715926876614
12.328645843199864
13.26266676131354
13.008979865698848
11.920033093079835
10.842896411731886
11.026687018657183
12.01198249491688
11.375735675109013
13.300042198654296
13.17310244385078
13.591694263339376
13.612735558539608
12.34705593614672
11.586977342868522
12.306867383337586
12.026579544200558
13.061124753736175
13.60178747433304
13.429147077408745
12.819639122253534
11.208150800996007
12.101024852239902
10.452488061838494
11.505245994427582
13.114471695762743
13.519666142006372
13.58747577911208
13.19038657722513
12.496265197595449
11.893164630123692
11.86428323205007
12.698675157113597
12.312782535262835
13.727415789423272
12.903064760441907
12.895570649369574
11.28756959255361
12.08558481949592
12.046442564916788
12.338418030872962
12.967364542576092
13.087548539944578
13.409665717751407
13.390705129258546
12.99845981258636
12.598628833746712
12.583402816549778
12.660098854758871
13.12645299947144
13.666446326996152
13.465409633904873
13.050888865711158
11.855487193066551
12.134891623584394
10.773616012227876
10.786984850066574
13.38643789704554
13.527770197387785
13.088651908987115
13.271975248634703
12.193789891106237
12.424533131102525
12.328989457050398
12.580464858678964
13.091889488623792
13.485228662536429
13.572600509617246
12.397769297969376
12.792367596683786
11.557847448965276
11.55464434961118
13.599826854127055
13.676384971205838
13.242038040528996
13.013066373672132
12.324017162507404
11.60640044273805
11.649423512570252
11.711639021071278
12.971000428925326
12.1410481374877
13.713245582258423
13.25802262394268
12.168287560725387
12.486564348438035
12.263091692164949
11.709263448499089
13.57122248728933
13.334139631199488
13.141619567905307
13.289045366462004
12.50342401764408
12.251915324708197
12.570636789168589
12.15690787849894
12.845996325847295
13.178351769629671
12.54221671349637
12.971534278817668
12.352117403834315
12.19264371895429
11.424461070294685
12.04221337991214
13.14236862231996
12.966441897773285
12.956972898791836
13.152833982570431
12.328083457901243
11.99845433439316
12.12977902996056
11.93443158349487
12.842550675539885
13.42394412166504
13.28392445001134
12.773963448613245
12.42601935017922
11.873051924602578
12.332124784814596
12.42183772418502
13.018951801215849
13.06951297420505
13.216962552266978
12.673223952668987
12.068097371351882
12.066398325703403
11.0439259709716
11.770077155166971
13.403591243141136
13.156348593443
13.27205134305143
12.594863349093998
11.571859522420368
11.789103137299207
11.111974592104843
12.762023759038694
13.539718209789156
13.114589404313625
12.538603417677106
11.98625901513742
12.02079874647984
12.158556987186444
11.79435365205336
12.913670419773208
12.947612096559167
12.345881228588496
12.276027743008513
12.381867942823988
11.097333550736494
12.342559231708265
12.445499520861294
12.868686729735032
12.810044091894383
12.64798319684564
13.308667025200176
11.006640895750706
12.062041920345791
12.067417277502386
11.72672949508842
12.852903083140522
13.03803604313589
12.897767875652558
12.856621008782778
11.845508123697982
11.858794922243646
11.208997351382097
11.880480642035536
12.864281576391704
13.0351373214487
12.999205300075229
13.535063371640945
12.222561903455816
12.336732063952354
11.931713586047408
11.825597543971298
13.10658760080469
12.58715403349936
13.643244663746032
13.280150642531796
12.194777929548422
11.648408127697053
12.462579150490685
12.653286026511296
13.30073418225641
13.07562549602369
13.252688880920235
13.209451795540982
12.19927820091266
12.210605568227606
13.076118920757152
12.980989010095982
13.062061666242132
13.159036866508927
13.58086983255998
12.273252674748507
11.627547556736545
12.065742011359134
12.329256976484206
12.995018918179994
12.721216939093669
13.272354531743073
13.385756614220778
12.580779937123229
12.22194720324569
12.83079527713085
11.493427580329694
12.96811003006496
12.682427810167155
12.706229905924255
12.211228591264554
12.33012968432604
11.5773383204247
12.269415851580105
11.626673659919447
13.081480010210612
12.811180752244244
13.191568418634915
13.609920065120718
12.924540031612535
12.401376648912333
12.814962882550615
11.856062657093048
13.049752205361305
13.05947445607342
13.075392456872464
13.05582073509527
12.740083598540878
12.441817264476864
12.072959091195573
12.110666252634246
13.268799495711615
12.70100673760112
13.352572314676308
12.516380281067086
12.262895511246828
12.282366170126808
12.523832778005271
11.825346670191152
12.148378169973968
13.013377885190607
13.350167017722589
13.289045366462004
12.27445710668826
11.9989453811761
12.396713487937287
12.74501071202394
12.525075257153386
12.513873921216147
12.635785499639384
12.95842582656121
12.266068886219388
12.194961031738671
12.788550986094831
12.850494219261009
12.902548745178482
12.681533700770611
12.926714667365555
13.36229932128947
11.40986045408522
11.845149053169052
12.265967823322176
12.290936303810671
13.142808543166666
13.165792623943954
12.697762024112876
13.088241712521944
12.10515891922364
11.715537670953267
12.071025817420605
12.94348991932804
13.101950597285398
13.163996082324044
13.022876608553588
13.039220262496205
12.31034513597706
12.520483434694032
11.698169120335365
12.427242805723154
13.2331706630298
13.377779779192338
13.157243891814804
12.876431714587508
11.429526104908064
11.5992606462936
12.822819631077664
11.521722813599467
13.404276092891678
13.385139536060134
13.263252926117383
13.420776691568786
12.000877465975805
12.942174912688984
12.47402065943072
12.3883656926273
13.258322245708538
13.115792647278113
13.35213120485434
12.646141474165802
12.546678937652242
11.997655343017527
12.54091716353571
12.73822404123212
13.433345349056598
13.23895621665156
13.056661340605045
13.327993818073534
12.12657355265594
11.796057453602884
12.391248957636094
12.118376757204146
12.87100166456889
13.091543496822734
12.697366095350844
12.104865242334084
12.687150419905263
12.413563645341238
12.029765997900997
12.088994800545493
13.433345349056598
13.58534156851795
13.000017370178735
12.639195480688954
12.835376398812858
12.75147754847046
12.375023012244355
11.719574241965574
13.500762624326054
13.527425394561991
13.19120815913072
13.498897122140992
12.25346099254796
12.40983026302058
12.826353265554417
11.949425750515845
13.251340582973851
12.87241178922886
13.130466979953775
13.0119166345944
12.747118765162329
11.842011347454331
12.196422282334876
11.302233224451925
8.370915780473524
13.235235913058771
13.089773112658577
12.809572068715624
12.352019907862882
12.39556612681008
12.364210471217577
12.257708012181524
13.039381963131746
13.041607724821002
12.90867434572499
13.435172804033297
12.20410425149851
12.608934871312162
12.064605351009275
11.086392600381489
13.38570311033402
13.143431566203612
12.708711297294712
13.10464481522763
12.621901835512515
11.741973346914278
12.944757366956654
12.337897259708487
13.28699914003721
13.126612322156465
13.251677062972814
12.618264760188026
12.389719935449987
12.005161343842474
11.94313250445748
13.624899964438558
13.464523847335158
13.348010216598482
13.382184932535663
12.726226091869766
12.315300784866396
11.060516931768577
13.2026116208624
13.408305530052417
12.897000986608989
13.1553486652482
12.29629620428886
12.176235860347564
11.45375028688295
13.289951365611165
13.519496118543998
13.633780420665628
13.46315890373512
12.68146592918072
12.55115899643704
12.651971019872237
11.47072171976356
13.547056565102256
13.316137356767287
12.97653986466798
13.2520313776007
12.1523338906685
12.107931609533123
11.627909005215995
12.539199094283044
13.170455784919
12.4638370863172
13.005072892990032
13.178872540794146
11.695937413769798
11.97712887410546
11.702813257706223
12.111976503372262
13.010237801525363
12.880090191466708
13.385826763761203
13.40697863366074
11.619156958317149
12.13489637948544
12.02188546986872
12.570901930651871
13.595628582479208
13.07534133093623
13.246768973093932
13.325865552355705
12.433587177717753
10.20260232013436
11.69439769080634
12.629033309130136
13.146049689729123
12.803196783364232
12.922474781583563
12.608943194138988
11.666348575415668
12.117890466322253
12.260632891324466
12.745733608982842
12.999803354631696
13.225162914644551
13.235575959983516
11.792419189303132
12.561956080785423
12.049640908369838
11.922886633707094
13.617232262978064
13.133544047930172
13.141877575537029
12.487678418257923
11.921977067632156
11.733255780298007
12.342023003865387
11.68653024150194
9.02457276503344
8.371896685064144
8.143834584282217
8.219709040585713
5.525216445065439
5.619604435163524
13.029620476236005
12.643809893678275
12.806227481305427
13.02222029420932
11.142984255896296
11.814721987255666
10.755805162812749
12.228902708524627
13.23539880266958
13.116672488971515
13.292146213943624
13.012232902013915
11.22997681986874
11.238040450091262
11.747239318346828
12.26839927773165
13.230705917313
13.243633645329735
13.287119226538604
13.456229555911936
12.318379041818051
12.485236263071103
12.470142222128178
12.432297139559182
12.89302267538449
12.906958654422857
12.928159272308108
13.01067296647102
11.808886496672926
11.589044970848022
12.06334741518276
12.155350320906564
12.977554060565923
13.195817816219009
13.52941217222372
13.12148070492844
12.041083853413852
11.437664640572052
12.366253130716586
13.386009865951449
13.277184149254705
13.31463092511115
12.810784823482203
12.340589099700196
12.659575705643874
11.760157534561472
12.611890663811891
13.058780094520788
13.525480231034404
12.974990629902432
13.008461472484896
12.794103500565368
12.390161045271949
12.990719583634927
13.45131314320622
12.785640374655028
12.989269033816072
11.933111820954764
12.4215892283554
11.917482741144228
11.842209906322978
12.932864047417294
13.394947392991076
12.996588365524987
12.846425545916643
11.250422438463032
11.387148648642778
12.27222302217217
13.275763323817388
12.942080983643333
13.36658676608192
13.207179663816536
10.692180718627014
11.866567253527135
11.96584430989992
11.419308051511962
13.302945676242526
12.835648674147706
13.508827443523842
9.529626865527916
11.9381197847556
11.705677499110834
11.818967817913972
11.88530431467086
12.926611226517824
13.039205994793065
13.18755443815257
13.273454333859828
11.451827713885336
12.012340376470547
12.61172064034952
12.195783802619529
13.02692031341746
12.665492046544385
13.151885180311863
13.077095069446727
12.29573144103972
12.063026391862197
12.23802452672976
12.788484403480195
13.019433336196702
13.495131637488274
12.316511161682453
13.299156412084583
11.130027992473288
11.807451403532468
11.946745800276744
12.40925479899408
13.007082261181726
12.860030989832351
12.58480580735818
12.882692858313812
12.288710542121413
11.493262312768366
11.41931518536353
10.378236556766751
13.319300030962497
13.420410487188292
12.908192810744143
12.57126219015606
12.119025937696849
12.38462160952929
12.419298073026766
12.109361946772538
12.351772601008523
12.41883793960062
11.769467210857895
12.51051031020177
10.686730456028954
11.503411405599309
10.996242118114878
10.832758019678296
13.189385460055064
13.385825574785944
12.925115495639034
8.663853127416132
11.65524830237564
12.795392349748685
12.01957053503486
12.17233602149031
13.45015627027692
13.026740778152998
13.145143690579976
12.924958550904533
12.388330023369464
11.882809844572536
12.689967102299423
12.124533271107452
9.37932612478926
9.253160392880886
10.205591403941412
10.246979632789248
7.898666696415148
7.757082333317498
6.565127499955565
7.984866213888267
13.16802076358374
12.931037781415856
13.002570100064869
13.270839777260113
12.160679308027966
12.601873547234955
11.983579064898322
12.860508957887417
12.645940537346632
12.83529435951982
12.828114137916486
12.1784961023194
12.11412973757058
11.39878633850094
12.072255217840848
13.106807561228038
13.154831461009508
13.204712540149217
13.174064324837214
12.605536780015203
11.885501684564248
11.38316320356671
10.987944259765868
12.664528976582684
13.23701105312398
12.28332210623694
12.451966357307809
12.647933259884669
12.199637271441588
11.50485719951712
11.882325931641162
12.953751964808813
13.276051055830637
13.119287045571244
13.187628154618778
11.502967917826822
10.922719454878347
11.829920658021592
11.846361807935637
13.465811507543211
13.278217368756827
13.276051055830637
13.24612217055176
11.566984723848805
12.557798234296456
11.521442215437787
11.975535647255242
13.090912150958957
13.18942588521395
13.209863180981417
13.250578449831323
12.623155015437987
12.227049096092172
11.794190762442554
12.581890440017329
12.737591506393072
9.643407042138731
13.46968875587049
12.863005805936268
11.95070152097128
11.66919854911714
11.748963332475796
13.121045539982791
13.455466233794136
13.125013150429936
11.772093657210236
10.620623431497506
11.728807823845273
12.169597811463404
13.357514884837771
12.807720834233695
13.2758120718031
12.239488155276494
11.76820808605612
11.907563120538724
12.189828225535392
13.132545308710636
12.957447299921114
12.377706529409242
12.15896599467635
12.305094621222906
12.053475353587714
11.714091877035456
13.480117257887857
13.47993177774708
13.362638179238957
13.43533688261937
11.954490785129224
12.09269845848462
12.42625476728097
11.8177300946669
12.960662289027828
13.198537002641729
12.821740041540348
13.131584616699456
12.24001011541623
12.824488952344607
11.917374544395445
12.076785213586618
9.732439887659666
13.023107269754291
13.23896572845365
12.663133119625854
11.410899618463644
12.20341107892114
11.56256411382708
12.00566546935329
13.301265654198229
12.4780643642946
13.417507009600056
13.4752543490689
12.841302251515458
12.362739708819271
12.145521062420926
12.265583784312753
7.9803671314992926
13.64011290290762
13.220686422785551
12.27136695998399
12.577845546178196
12.19889772882902
12.407887477443523
13.2361704476142
13.117030370525184
13.570500779305693
12.982455016593237
12.718131548290444
11.874917426787649
12.230585108519447
12.070174511133471
12.98199963906814
13.27159596552633
12.849898542655064
12.81757387222456
11.069498450892866
11.99233111179717
12.164080966250708
11.109279185187347
13.235712692138572
13.210828628893635
12.743314044325984
12.567997264088373
12.431573053625016
12.298400690501468
11.80803994628684
7.18455864264206
13.402014661944577
12.393490176003752
12.9366176423174
13.39554306959701
11.8452952971262
12.812246074078416
12.498325691723377
13.078155635379858
12.940919354812989
13.209058244729476
9.828460340791594
10.688532942525171
12.257926783629618
11.582513929737388
11.94761731914332
13.697152802095957
13.084788928362972
12.834018589064383
12.78908364701192
11.56447360809682
11.206978471388313
11.86607858469472
12.74290979273712
13.39545508542767
13.284887519973044
13.74990287854132
13.706971359804244
12.68895052845096
12.04482318061082
12.150792978729784
12.547199708816716
13.29111656136729
13.035691383920494
13.391744293636975
12.959252164367856
12.463273512043315
12.40184748311583
11.61107192653992
10.387087288612292
12.9118893348317
13.039205994793065
13.468151410857562
12.922008703281108
12.901413273803882
12.112494896586211
11.901965425008257
12.421341921501044
13.333782938621088
13.800479508208925
13.6134406208696
13.284990960820778
12.213800344754873
12.163694549290769
11.562300161319058
12.019348196660983
13.158475670185569
13.218356031273288
13.487530518642416
12.851151722580536
11.215332211574603
11.74090683610484
12.151563434699142

In [14]:
merged_df = p.merge(trials, scores, on=['modelid', 'segmentid'], how='inner')

In [15]:
merged_df

,modelid,segmentid,targettype,LLR
0,id10001-1zcIwhmdeo4-00001,id10001-9mQ11vBs1wc-00003,target,12.836136
1,id10001-1zcIwhmdeo4-00001,id10001-J9lHsKG98U8-00021,target,12.904310
2,id10001-1zcIwhmdeo4-00001,id10001-J9lHsKG98U8-00024,target,13.093880
3,id10001-1zcIwhmdeo4-00001,id10001-zELwAz2W6hM-00009,target,13.284470
4,id10001-1zcIwhmdeo4-00001,id10104-MSV9xFqcEh8-00006,nontarget,-6.010812
...,...,...,...,...
99995,id10111-NtICHG3PV6A-00005,id10111-3FIiSPMPF1Y-00019,target,12.567023
99996,id10111-NtICHG3PV6A-00005,id10111-Mx9hN4LD_oI-00001,target,12.869458
99997,id10111-NtICHG3PV6A-00005,id10111-rUFh-NA1DH8-00008,target,12.534912
99998,id10111-NtICHG3PV6A-00005,id10111-vYeUCJ1iPYI-00006,target,12.976408
99999,id10111-NtICHG3PV6A-00005,id10400-_DvLV9aicU4-00018,nontarget,12.389861

In [16]:
nb_non_tar = 0
imposter = 0

for i, row in merged_df.iterrows():
    score = row['LLR']

    if row['targettype'] == 'nontarget':
        nb_non_tar = nb_non_tar + 1

        if float(score) > t:
            imposter = imposter + 1

In [17]:
nb_non_tar

50255

In [18]:
imposter

47651

In [19]:
asr = imposter/nb_non_tar

In [20]:
asr

0.9481842602726097